export { ApiError, BaseHttpClient, FFPClient, ffpClient } from './client';
export type {
  ApiErrorResponse,
  ClientConfig,
  ErrorInterceptor,
  HttpMethod,
  RequestConfig,
  RequestContext,
  RequestInterceptor,
  ResponseInterceptor,
} from './client';

// Endpoint exports
export {
  adminVideosApi,
  assessmentsApi,
  exercisesApi,
  programmesApi,
  sessionsApi,
  usersApi,
  videosApi,
} from './endpoints';
export type {
  ActiveProgrammeResponse,
  ProgrammeDetailResponse,
  ProgressSummaryResponse,
  AssessmentFlow,
  AssessmentResultsResponse,
  AssessmentTemplate,
  CreateVideoInput,
  PaginatedAdminVideoResponse,
  UpdateVideoInput,
  SaveProgressRequest,
  SaveProgressResponse,
  StartAssessmentResponse,
  SubmitAssessmentRequest,
  SubmitAssessmentResponse,
  SignedVideoUrlResponse,
  VideoDetailResponse,
  VideoFilterInput,
  VideoListApiResponse,
  VideoListResponse,
  SessionStatusResponse,
  StartSessionRequest,
  StartSessionResponse,
  ToggleExerciseCompletionResponse,
  UserProfileResponse,
  UploadUrlRequest,
  UploadUrlResponse,
} from './endpoints';
