/**
 * Mock video catalogue for the prototype — a faithful stand-in for the real Video
 * Library (the surface that today supplies "exercises" to programmes and templates).
 *
 * The shape mirrors the live admin video row: title, description, status, movement
 * type, difficulty, duration, body parts, equipment, free-form tags, timestamps.
 * The last two fields — `goals` and `essential` — are the *iteration* the programme
 * model needs on top of today's library, and are surfaced as new columns. Throwaway.
 */
import { type GoalId } from './prototype-programmes';

export type VideoStatus = 'draft' | 'active' | 'archived';
/** The live video library's movement-type enum (note: no "cardio" — see the iteration callout). */
export type VideoMovementType = 'stretch' | 'strength' | 'mobility' | 'balance';
export type VideoDifficulty = 'beginner' | 'intermediate' | 'advanced';

export interface PrototypeVideo {
  id: string;
  publicId: string;
  title: string;
  description: string | null;
  status: VideoStatus;
  movementType: VideoMovementType;
  difficulty: VideoDifficulty;
  durationSeconds: number;
  bodyParts: string[];
  equipment: string[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
  // --- Programme-model additions (the iteration on top of today's library) ---
  /** New: the goal axis the assembler tags exercises by. */
  goals: GoalId[];
  /** New: marks a core, must-have exercise for the essential thread. */
  essential: boolean;
}

export const VIDEO_MOVEMENT_LABELS: Record<VideoMovementType, string> = {
  stretch: 'Stretch',
  strength: 'Strength',
  mobility: 'Mobility',
  balance: 'Balance',
};

export const VIDEO_LIBRARY: PrototypeVideo[] = [
  {
    id: 'vid-neck-release',
    publicId: 'vneckrelease',
    title: 'Neck rolls & shoulder release',
    description: 'Gentle mobility to ease desk-related neck and shoulder tension.',
    status: 'active',
    movementType: 'mobility',
    difficulty: 'beginner',
    durationSeconds: 240,
    bodyParts: ['Neck', 'Shoulders'],
    equipment: [],
    tags: ['warm-up', 'good for beginners', 'low impact'],
    createdAt: '2026-05-02T09:00:00.000Z',
    updatedAt: '2026-05-02T09:00:00.000Z',
    goals: ['relieve'],
    essential: false,
  },
  {
    id: 'vid-cat-cow',
    publicId: 'vcatcow00001',
    title: 'Upper-back cat-cow',
    description: 'Flowing spinal mobility for the upper back and neck.',
    status: 'active',
    movementType: 'mobility',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Lower back', 'Neck'],
    equipment: ['Yoga mat'],
    tags: ['good for beginners'],
    createdAt: '2026-05-04T09:00:00.000Z',
    updatedAt: '2026-06-01T11:30:00.000Z',
    goals: ['relieve', 'strength'],
    essential: true,
  },
  {
    id: 'vid-spinal-twist',
    publicId: 'vspinaltwist',
    title: 'Seated spinal twist',
    description: 'A seated rotational stretch to decompress the spine.',
    status: 'active',
    movementType: 'stretch',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Lower back'],
    equipment: ['Chair'],
    tags: ['good for beginners', 'low impact'],
    createdAt: '2026-05-06T09:00:00.000Z',
    updatedAt: '2026-05-06T09:00:00.000Z',
    goals: ['relieve'],
    essential: true,
  },
  {
    id: 'vid-hip-flexor',
    publicId: 'vhipflexor01',
    title: 'Standing hip-flexor stretch',
    description: 'Opens tight hip flexors from prolonged sitting.',
    status: 'active',
    movementType: 'stretch',
    difficulty: 'beginner',
    durationSeconds: 240,
    bodyParts: ['Hips'],
    equipment: [],
    tags: ['good for beginners'],
    createdAt: '2026-05-08T09:00:00.000Z',
    updatedAt: '2026-05-08T09:00:00.000Z',
    goals: ['relieve'],
    essential: true,
  },
  {
    id: 'vid-glute-stretch',
    publicId: 'vglutestretc',
    title: 'Glute & hamstring stretch',
    description: 'Lengthens the posterior chain to ease lower-body tightness.',
    status: 'active',
    movementType: 'stretch',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Hips', 'Hamstrings'],
    equipment: ['Yoga mat'],
    tags: ['low impact'],
    createdAt: '2026-05-10T09:00:00.000Z',
    updatedAt: '2026-05-10T09:00:00.000Z',
    goals: ['relieve'],
    essential: false,
  },
  {
    id: 'vid-balance-stand',
    publicId: 'vbalancesta1',
    title: 'Single-leg balance hold',
    description: 'Builds ankle and hip stability through static balance.',
    status: 'draft',
    movementType: 'balance',
    difficulty: 'beginner',
    durationSeconds: 180,
    bodyParts: ['Ankles', 'Hips'],
    equipment: [],
    tags: ['good for beginners'],
    createdAt: '2026-06-12T09:00:00.000Z',
    updatedAt: '2026-06-12T09:00:00.000Z',
    goals: ['strength'],
    essential: false,
  },
  {
    id: 'vid-wall-press',
    publicId: 'vwallpress01',
    title: 'Wall press-ups',
    description: 'Accessible upper-body strength against a wall.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Chest', 'Shoulders'],
    equipment: [],
    tags: ['good for beginners'],
    createdAt: '2026-05-12T09:00:00.000Z',
    updatedAt: '2026-05-12T09:00:00.000Z',
    goals: ['strength'],
    essential: false,
  },
  {
    id: 'vid-dead-bug',
    publicId: 'vdeadbug0001',
    title: 'Dead bug core hold',
    description: 'Anti-extension core control for a stable trunk.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'intermediate',
    durationSeconds: 360,
    bodyParts: ['Core'],
    equipment: ['Yoga mat'],
    tags: [],
    createdAt: '2026-05-14T09:00:00.000Z',
    updatedAt: '2026-06-03T15:00:00.000Z',
    goals: ['strength'],
    essential: true,
  },
  {
    id: 'vid-glute-bridge',
    publicId: 'vglutebridge',
    title: 'Glute bridge',
    description: 'Posterior-chain strength for hips and lower back.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Hips', 'Core'],
    equipment: ['Yoga mat'],
    tags: ['good for beginners'],
    createdAt: '2026-05-16T09:00:00.000Z',
    updatedAt: '2026-05-16T09:00:00.000Z',
    goals: ['strength'],
    essential: true,
  },
  {
    id: 'vid-bird-dog',
    publicId: 'vbirddog0001',
    title: 'Bird-dog',
    description: 'Contralateral core and back stability drill.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'intermediate',
    durationSeconds: 300,
    bodyParts: ['Core', 'Lower back'],
    equipment: ['Yoga mat'],
    tags: [],
    createdAt: '2026-05-18T09:00:00.000Z',
    updatedAt: '2026-05-18T09:00:00.000Z',
    goals: ['strength'],
    essential: false,
  },
  {
    id: 'vid-goblet-squat',
    publicId: 'vgobletsquat',
    title: 'Goblet squat',
    description: 'Loaded lower-body strength with a front-held weight.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'intermediate',
    durationSeconds: 360,
    bodyParts: ['Hips', 'Legs'],
    equipment: ['Dumbbell'],
    tags: [],
    createdAt: '2026-05-20T09:00:00.000Z',
    updatedAt: '2026-05-20T09:00:00.000Z',
    goals: ['strength'],
    essential: false,
  },
  {
    id: 'vid-plank',
    publicId: 'vplank000001',
    title: 'Plank progression',
    description: 'Isometric full-body bracing with progressions.',
    status: 'archived',
    movementType: 'strength',
    difficulty: 'advanced',
    durationSeconds: 300,
    bodyParts: ['Core', 'Full body'],
    equipment: ['Yoga mat'],
    tags: [],
    createdAt: '2026-04-22T09:00:00.000Z',
    updatedAt: '2026-05-30T10:00:00.000Z',
    goals: ['strength'],
    essential: false,
  },
  {
    id: 'vid-marching',
    publicId: 'vmarching001',
    title: 'Marching on the spot',
    description: 'Low-impact aerobic warm-up to raise the heart rate.',
    status: 'active',
    movementType: 'mobility',
    difficulty: 'beginner',
    durationSeconds: 300,
    bodyParts: ['Full body', 'Hips'],
    equipment: [],
    tags: ['warm-up', 'good for beginners', 'low impact', 'cardio'],
    createdAt: '2026-05-24T09:00:00.000Z',
    updatedAt: '2026-05-24T09:00:00.000Z',
    goals: ['energy'],
    essential: true,
  },
  {
    id: 'vid-step-touch',
    publicId: 'vsteptouch01',
    title: 'Step-touch cardio',
    description: 'Rhythmic side-stepping for a gentle cardio block.',
    status: 'draft',
    movementType: 'mobility',
    difficulty: 'beginner',
    durationSeconds: 360,
    bodyParts: ['Full body'],
    equipment: [],
    tags: ['low impact', 'cardio'],
    createdAt: '2026-06-15T09:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
    goals: ['energy'],
    essential: false,
  },
  {
    id: 'vid-lunge-flow',
    publicId: 'vlungeflow01',
    title: 'Dynamic lunge flow',
    description: 'Moving lunge sequence blending strength and conditioning.',
    status: 'active',
    movementType: 'strength',
    difficulty: 'intermediate',
    durationSeconds: 420,
    bodyParts: ['Hips', 'Legs', 'Full body'],
    equipment: [],
    tags: ['cardio'],
    createdAt: '2026-05-28T09:00:00.000Z',
    updatedAt: '2026-05-28T09:00:00.000Z',
    goals: ['energy', 'strength'],
    essential: false,
  },
];
