export const ASSESSMENT_ACTION = {
  START_ASSESSMENT: 'START_ASSESSMENT',
  SET_ANSWER: 'SET_ANSWER',
  NEXT_STEP: 'NEXT_STEP',
  PREV_STEP: 'PREV_STEP',
  SET_PHASE: 'SET_PHASE',
  GO_TO_STEP: 'GO_TO_STEP',
  MARK_SAVED: 'MARK_SAVED',
  SET_SCORES: 'SET_SCORES',
  ADD_WARNING: 'ADD_WARNING',
  CLEAR_WARNINGS: 'CLEAR_WARNINGS',
  RESET: 'RESET',
} as const;
