export const ASSESSMENT_ACTION = {
  START_ASSESSMENT: 'START_ASSESSMENT',
  SET_ANSWER: 'SET_ANSWER',
  CLEAR_ANSWER: 'CLEAR_ANSWER',
  NEXT_STEP: 'NEXT_STEP',
  PREV_STEP: 'PREV_STEP',
  MARK_SAVED: 'MARK_SAVED',
  SET_SCORES: 'SET_SCORES',
} as const;
