/**
 * Auto-generated icon types from Icomoon selection.json
 * DO NOT EDIT MANUALLY - Run 'pnpm icon:generate' to update
 *
 * Generated: 2025-11-16T19:09:55.775Z
 * Total icons: 66
 */

export enum Icons {
  ACTIVITY = 'Activity',
  ALERTCIRCLE = 'AlertCircle',
  ALERTTRIANGLE = 'AlertTriangle',
  ARROWDOWN = 'ArrowDown',
  ARROWLEFT = 'ArrowLeft',
  ARROWRIGHT = 'ArrowRight',
  ARROWUP = 'ArrowUp',
  AWARD = 'Award',
  BARCHART3 = 'BarChart3',
  BELL = 'Bell',
  BUILDING = 'Building',
  CALENDAR = 'Calendar',
  CAMERA = 'Camera',
  CHECK = 'Check',
  CHECKCIRCLE = 'CheckCircle',
  CHEVRONDOWN = 'ChevronDown',
  CHEVRONLEFT = 'ChevronLeft',
  CHEVRONRIGHT = 'ChevronRight',
  CIRCLE = 'Circle',
  CLIPBOARDLIST = 'ClipboardList',
  CLOCK = 'Clock',
  CLOSE = 'Close',
  COPY = 'Copy',
  CREDITCARD = 'CreditCard',
  DOLLARSIGN = 'DollarSign',
  DOWNLOAD = 'Download',
  EDIT = 'Edit',
  FILETEXT = 'FileText',
  FILTER = 'Filter',
  GLOBE = 'Globe',
  GRIPVERTICAL = 'GripVertical',
  HEART = 'Heart',
  HELPCIRCLE = 'HelpCircle',
  HOME = 'Home',
  LOGOUT = 'LogOut',
  MAIL = 'Mail',
  MAXIMIZE = 'Maximize',
  MENU = 'Menu',
  MOREHORIZONTAL = 'MoreHorizontal',
  PANELLEFT = 'PanelLeft',
  PAUSE = 'Pause',
  PHONE = 'Phone',
  PLAY = 'Play',
  PLUS = 'Plus',
  RECEIPT = 'Receipt',
  REPEAT = 'Repeat',
  SAVE = 'Save',
  SEARCH = 'Search',
  SETTINGS = 'Settings',
  SHIELD = 'Shield',
  SKIPBACK = 'SkipBack',
  SKIPFORWARD = 'SkipForward',
  TARGET = 'Target',
  TRASH2 = 'Trash2',
  TRENDINGDOWN = 'TrendingDown',
  TRENDINGUP = 'TrendingUp',
  UPLOAD = 'Upload',
  USER = 'User',
  USERCHECK = 'UserCheck',
  USERPLUS = 'UserPlus',
  USERS = 'Users',
  VIDEO = 'Video',
  VISIBILITY = 'Visibility',
  VISIBILITYOFF = 'VisibilityOff',
  VOLUME2 = 'Volume2',
  ZAP = 'Zap',
}

export type IconName = `${Icons}`;
